### ISSUE TITLE
[IDEA] ShowAV脚本显示功能请求

### ISSUE THREAD

**Issue by wdpd** [CKylinMC/UserJS#27]
### 目标

脚本：视频页面常驻显示AV/BV号

### 描述你的想法

希望可以自定义文字信息，如分p标题目前是标题两边加书名号，我希望能够不加书名号。虽然可以修改代码实现，但更新之后仍会恢复。

**Comment by CKylinMC** [comment]
在[Greasyfork](https://greasyfork.org/zh-CN/scripts/398655/discussions/99054)上其实有人提过这个。

我之后会允许像自定义复制一样自定义栏位中的组件。现在复制分P标题应该是不加书名号的。

不过既然都不喜欢书名号，那我之后把书名号从脚本里清出去吧...
