### ISSUE TITLE
[IDEA] [关注管理器] 按照最后投稿时间排序或筛选

### ISSUE THREAD

**Issue by cclfly** [CKylinMC/UserJS#68]
### 目标

脚本：关注管理器

### 描述你的想法

希望关注管理器能有按照up的最后投稿时间进行排序或筛选的功能，最好能对不同投稿类型分别排序（动态、视频、专栏、直播）。因为关注主要是为了关注新作品，一些up退坑退圈就没必要占着关注位了。另外谢谢作者，目前关注管理器已经帮大忙了（见一个关注一个，关注数常年保持2000）。

**Comment by CKylinMC** [comment]
感谢你的反馈。

不过很遗憾，目前因为B站官方接口调用的限制，还做不到这一点。

> 由于B站API调用频率限制，这些功能可能无法实现或需要帮助：
> 
> * 自动分类所有UP主
> * 按照最后投稿时间排序
> * 按照粉丝量排序
> * 按照是否封号排序

我也会关注这些功能，如果发现可用的方法，会尽快添加。

**Comment by cclfly** [comment]
明白了，谢谢作者。
