### ISSUE TITLE
[Bug] ShowAV脚本

### ISSUE THREAD

**Issue by whyjxz14** [CKylinMC/UserJS#76]
### 目标

脚本：视频页面常驻显示AV/BV号

### 脚本版本号

1.17.5

### 描述出现的问题

组件: 显示视频投稿时间
隐藏原版发布时间 (点击切换)

在有警告的页面，比如 
https://www.bilibili.com/video/av510953025/
选择隐藏原版发布时间，
然后就把弹幕数隐藏了。发布时间没有隐藏

**Comment by CKylinMC** [comment]
emm视频404了...

**Comment by whyjxz14** [comment]
> emm视频404了...

这个视频复制到地址栏能打开。点击链接你可能打不开

**Comment by whyjxz14** [comment]
![image](https://user-images.githubusercontent.com/6323818/166941008-5cff4b6d-dd59-4ca5-a064-5a5798ae980b.png)

**Comment by whyjxz14** [comment]
更新了。没回复

**Comment by CKylinMC** [comment]
> 更新了。没回复

我看到了你的回复，~~*`其实之前打了回复但是忘记按Comment了`*~~。

我在gf反馈那里，一个月之前有人反馈过类似的问题，和你这个类似的，都是在信息条带图标的一种新版本的组件。我当时还想等等我这里就能也被灰度到这个，就能修复了。结果我这里一个月了都没有拿到，所以没办法直接的修复，只能靠猜，以及和找朋友看看有没有人刷到了。

在我能弄到这个新版本的条之前可能不容易修复了。

如果较为影响，还请暂时关闭相关功能，使用原版的时间和热度显示。另一个issue提到的宽度问题这几天抽空会更新。

*回复慢是因为这两天在慢毕业的事情，基本上我脚本更新全都被搁置了，学校这边事情比较多，抱歉。*
