### ISSUE TITLE
[IDEA] ShowAV脚本显示警告

### ISSUE THREAD

**Issue by whyjxz14** [CKylinMC/UserJS#77]
### 目标

脚本：视频页面常驻显示AV/BV号

### 描述你的想法

![image](https://user-images.githubusercontent.com/6323818/166893337-d636b732-cd7a-489f-b4d0-ee579bf5ee2f.png)
 视频警告文字折叠的有一点丑。是不是该让图标显示完整

**Comment by CKylinMC** [comment]
原本的处理方法是给这个折叠设置一个固定宽度，可能在一些情况下有这个问题，那我之后换个方法吧
