### ISSUE TITLE
[IDEA] 按粉丝数量和最近投稿时间排序

### ISSUE THREAD

**Issue by xushet** [CKylinMC/UserJS#78]
### 目标

脚本：关注管理器

### 描述你的想法

不知道能不能实现

**Comment by CKylinMC** [comment]
可以尝试一下。

不过得等一阵，最近正在忙毕业...

<details>
<summary>给我自己码个备注</summary>
https://api.bilibili.com/x/web-interface/card?mid=
</details>

**Comment by FreezeSoul** [comment]
期待，也需要这个功能

**Comment by happymy** [comment]
是的，非常需要这个功能。

**Comment by CKylinMC** [comment]
0.2.22，更多 - 实验性功能 里面开启

我尝试加了一下，不过没有完整测试。

我还是觉得这个功能在关注数量比较多的时候会导致被风控或封号，请小心使用。

**Comment by happymy** [comment]
刚刚试了，排序顺序不对，为了更好的debug能不能把最后更新的时间显示出来。
测试的是2900+的关注，已经实名认证的账号。

**Comment by CKylinMC** [comment]
> 刚刚试了，排序顺序不对，为了更好的debug能不能把最后更新的时间显示出来。 测试的是2900+的关注，已经实名认证的账号。

按F12去Console，超过20个连续获取应该就会出现风控，你后面数据不对的原因应该就是风控。

**Comment by CKylinMC** [comment]
脚本这个版本的debug我没关掉，你点开窗口然后F12到Console后会看到好多FoMan开头的日志，后面的数据行展开，如果成功填充会写一个字段叫lastUpdate，数字就是时间戳。

**Comment by happymy** [comment]
估计是太快了，触发风控。弄慢点少并发，加个进度条。按关注日期从旧到新的顺序。。。

**Comment by CKylinMC** [comment]
> 估计是太快了，触发风控。弄慢点少并发，加个进度条。按关注日期从旧到新的顺序。。。

这个风控是几分钟内多少次请求，不是少点并发的事情

**Comment by CKylinMC** [comment]
这约等于在爬虫爬每个人的个人空间动态和信息，这个API一直是B站风控重灾区

**Comment by happymy** [comment]
我试了https://blog.csdn.net/a3613110/article/details/125199515 脚本是有效的。
目前搭配Auto Highlight 标记和自己，和自己手动翻页。。。清理关注。

**Comment by CKylinMC** [comment]
那就不清楚了。

根据 [查询用户投稿视频明细 - BAC Document](https://socialsisteryi.github.io/bilibili-API-collect/docs/user/space.html#%E6%8A%95%E7%A8%BF) 这里的说明，CSDN中提到的接口已经废弃，而更换到新的WBI接口之后，我这里无论如何测试都是会风控的。由于B站会上传你的操作行为，不排除是你手动点击页面等帮你避开了风控，并且每个页面信息很少，所以没有关系。但是一次性加载3000条数据是肯定不可能的，要不然就要等待巨量的时间来让它过风控。

在找到更好的解决方案之前，这个功能暂时搁置。

**Comment by CKylinMC** [comment]
暂时无法实现
