### ISSUE TITLE
[Bug] 悄悄关注时会显示关注失败

### ISSUE THREAD

**Issue by Infinity1145** [CKylinMC/UserJS#88]
### 目标

脚本：关注管理器

### 脚本版本号

0.2.20

### 描述出现的问题

点击悄悄关注之后会显示关注失败
![Snipaste_2024-01-18_09-08-39](https://github.com/CKylinMC/UserJS/assets/154658017/b50d7dd8-deaf-4840-9174-41078c9b0043)

**Comment by CKylinMC** [comment]
我看到这个问题了，另外注意一个事情，转悄悄关注失败会下掉原有的关注，记得关注回去，抱歉。
