### ISSUE TITLE
[Bug] ShowAV: 适配最新页面

### ISSUE THREAD

**Issue by NightSharp** [CKylinMC/UserJS#89]
### 目标

脚本：视频页面常驻显示AV/BV号

### 脚本版本号

1.19.3

### 描述出现的问题

没有适配新版页面
[官方的视频信息栏好像改版了，请问适配需要多久~](https://greasyfork.org/zh-CN/scripts/398655-哔哩哔哩自定义视频信息条/discussions/190372)

**Comment by CKylinMC** [comment]
1.19.3 尝试适配当前B站页面

https://github.com/CKylinMC/UserJS/commit/cbddec569be12b2ba553fd7c78676c79e9952963#diff-a62222ba2c45f4794ec94606772a8c102c590ea3aa54c4714f5134dc0905ef0d

因为距离上次更新时间蛮久了，中间我不确定B站播放器做了什么修改，目前看已经可以正常替换信息条，暂时不确定有没有其他问题。

**Comment by CKylinMC** [comment]
更新这个事情是这样，我有时候有空一点有时候忙一点，有空时候就更新一些，没空时候只能暂时咕咕咕...

中间大概会按月间隔的样子，所以还是得看情况（

更新不及时这个事情，抱歉（

**Comment by NightSharp** [comment]
> 更新这个事情是这样，我有时候有空一点有时候忙一点，有空时候就更新一些，没空时候只能暂时咕咕咕...
> 
> 中间大概会按月间隔的样子，所以还是得看情况（
> 
> 更新不及时这个事情，抱歉（

大佬辛苦了
