### ISSUE TITLE
[IDEA] 请求增加排序条件，按关注的UP主的最后更新时间排序。

### ISSUE THREAD

**Issue by happymy** [CKylinMC/UserJS#90]
### 目标

脚本：关注管理器

### 描述你的想法

[IDEA] 请求增加排序条件，按关注的UP主的最后更新时间排序。
参考：https://blog.csdn.net/a3613110/article/details/125199515 可以获得UP主最后更新时间。

**Comment by CKylinMC** [comment]
dup #78 ，文中所提供的接口已失效，后续讨论合并到 #78
